from flask import Flask, request, jsonify
from playhouse.shortcuts import model_to_dict
from models.hero import Hero
from models import database
from flask_cors import CORS, cross_origin

app = Flask(__name__)
CORS(app)

# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    database.connect()

# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not database.is_closed():
        database.close()

@app.route("/heroes")
def index():
    heroes = []
    for hero in Hero.select():
        heroes.append(model_to_dict(hero))
    
    return jsonify(heroes)

@app.route("/heroes/<id>", methods=["GET"])
def show(id):
    hero = get_hero(id)
    return jsonify(model_to_dict(hero))

@app.route("/heroes/<id>", methods=["PUT"])
def update(id):
    hero = get_hero(id)
    hero.name = request.get_json()["name"]
    hero.save()
    return jsonify(model_to_dict(hero))

def get_hero(id):
    return Hero.get(Hero.id == id) 
